name: "windows_exe"

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: hello
      run: Get-ChildItem

    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make

    - run: gcc -v



